name: 🧪 Test Run

on:
  schedule:
    - cron: "30 23 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - name: 🔍 Checkout
        uses: actions/checkout@v7

      - name: 🔧 Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: 🔧 Setup uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39

      - name: 💾 Install dependencies
        run: uv pip install -e ".[dev]"

      - name: Run Smoke Test
        run: python tests/smoke_test.py

      - name: Run Task with Secrets
        env:
          HOYO_ASSISTANT_LANGUAGE: zh_CN
        run: |
          mkdir config
          curl ${{ secrets.CONFIG_1 }} -o config/config_1.yaml
          curl ${{ secrets.CONFIG_2 }} -o config/config_2.yaml
          python tests/test_tasks.py --multi
