name: 🧪 Test Run

on:
  schedule:
    - cron: "30 23 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - name: 🔍 Checkout
        uses: actions/checkout@v7

      - name: 🔧 Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: 🔧 Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: true

      - name: 💾 Install dependencies
        run: uv pip install -e ".[dev]"

      - name: 🧪 Run tests
        run: pytest -v --cov=hoyo_assistant --cov-report=term-missing

      - name: 🚀 Run task with secrets
        env:
          HOYO_ASSISTANT_LANGUAGE: zh_CN
        run: |
          mkdir -p config
          curl ${{ secrets.CONFIG_1 }} -o config/config_1.yaml
          curl ${{ secrets.CONFIG_2 }} -o config/config_2.yaml
          hoyo-cli --multi
